# Generated by Django 3.2.3 on 2021-06-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Psi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('o3_sub_index', models.FloatField()),
                ('pm10_twenty_four_hourly', models.FloatField()),
                ('pm10_sub_index', models.FloatField()),
                ('co_sub_index', models.FloatField()),
                ('pm25_twenty_four_hourly', models.FloatField()),
                ('so2_sub_index', models.FloatField()),
                ('updated_timestamp', models.DateTimeField()),
            ],
        ),
    ]
