# Generated by Django 3.2.3 on 2021-06-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psi',
            options={'ordering': ('-updated_timestamp',)},
        ),
        migrations.AlterField(
            model_name='psi',
            name='co_sub_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='psi',
            name='o3_sub_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='psi',
            name='pm10_sub_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='psi',
            name='pm10_twenty_four_hourly',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='psi',
            name='pm25_twenty_four_hourly',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='psi',
            name='so2_sub_index',
            field=models.FloatField(default=0),
        ),
    ]
